services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    # Remove platform if not using apple silicon.
    platform: linux/amd64
    hostname: metabase
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - '${MB_PORT:-8888}:3000'
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: '${MB_DB_DBNAME:-postgres}'
      MB_DB_PORT: '${MB_DB_PORT:-5432}'
      MB_DB_USER: '${MB_DB_USER:-postgres}'
      MB_DB_PASS: '${MB_DB_PASS:-postgres}'
      MB_DB_HOST: '${MB_DB_HOST:-metabase-postgres}'
    networks:
      - metanet1
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
  postgres:
    image: postgres:latest
    container_name: metabase-postgres
    hostname: '${MB_DB_HOST:-postgres}'
    environment:
      POSTGRES_USER: '${MB_DB_USER:-postgres}'
      POSTGRES_DB: '${MB_DB_DBNAME:-postgres}'
      POSTGRES_PASSWORD: '${MB_DB_PASS:-postgres}'
    networks:
      - metanet1
networks:
  metanet1:
    driver: bridge
