services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml:ro"
      - "./provider.yml:/etc/traefik/provider.yml:ro"

      # This is for the certs config so there is no need to generate them every time it starts.
      - "./letsencrypt:/letsencrypt"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik

# minimal echo example
#  echo-server:
#    image: mendhak/http-https-echo:36
#    ports:
#      - 3001:8080

networks:
  traefik:
    driver: bridge
