services:
  inngest:
    build: .
    command: bash /app/entrypoint.sh
    entrypoint: /app/entrypoint.sh
    ports:
      - "8288:8288"
    networks:
      - inngestnet
    volumes:
      - ./inngest.yml:/app/config/inngest.yml
      - inngest_data:/app/data
    environment:
      INNGEST_DEV: 0
      INNGEST_EVENT_KEYS: ${INNGEST_EVENT_KEYS:-local,development,production}
      INNGEST_SIGNING_KEY: ${INNGEST_SIGNING_KEY:-local-signing-key}
      INNGEST_REDIS_URI: ${INNGEST_REDIS_URI:-redis://inngest-redis:6379}
      INNGEST_POSTGRES_URI: ${INNGEST_POSTGRES_URI:-postgresql://postgres:postgres@inngest-postgres:5432/inngest}


  redis:
    image: redis:latest
    container_name: inngest-redis
    networks:
      - inngestnet
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: inngest-postgres
    networks:
      - inngestnet
    environment:
      POSTGRES_USER: '${DB_USER:-postgres}'
      POSTGRES_DB: '${DB_DBNAME:-inngest}'
      POSTGRES_PASSWORD: '${DB_PASS:-postgres}'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  inngest_data:
  redis_data:
  postgres_data:

# We need bridging to work with the host machine.
networks:
  inngestnet:
    driver: bridge
